### PR TITLE
Fixes issue with hard-refresh not working.

### LINKED ISSUE #603: "Hard refresh" in runner doesn't work if on non-standard Office.js library
If using default library, all is great.
But if use a debug or beta version, hard-refresh doesn't work.

### PR DESCRIPTION
**Pull request by Zlatkovsky**
The problem was that if window.location.search didn't need to change, it was no-op-ing and not reloading the page.
This fix should help detect whether it will be a no-op, and, if so, do a forced "window.location.reload()"

Fixes #603

### CODE REVIEW

File: packages/runner/src/pages/Runner/components/App/index.tsx [hunk 1]
```diff
@@ -236,8 +236,16 @@ export class App extends React.Component<{}, IState> {
       newQueryParams[OFFICE_JS_URL_QUERY_PARAMETER_KEY] = newOfficeJsUrl;
     }
 
-    const newParams = queryString.stringify(newQueryParams);
-    window.location.search = newParams;
+    const newParams = '?' + queryString.stringify(newQueryParams);
```
Comment (nico-bellante) [inline packages/runner/src/pages/Runner/components/App/index.tsx]: instead of stringifying and getting this weird if statement, conversely couldn't you parse the existing params and compare it to newQueryParams

Comment (Zlatkovsky) [reply packages/runner/src/pages/Runner/components/App/index.tsx]: Hm, you're right.  Actually, the whole code block is highly questionable code.  Let me rework it.
This would be one place where I think you were too liberal with pre-approving :-)

File: packages/runner/src/pages/Runner/components/App/index.tsx [hunk 2]
```diff
@@ -228,16 +228,25 @@ export class App extends React.Component<{}, IState> {
   // and thus will get invoked with an object-based click-event parameter
   // rather than a string, messing up the reload.
   private reloadPageWithDifferentOfficeJsUrl(newOfficeJsUrl: string | null) {
-    const newQueryParams: { [key: string]: any } = queryString.parse(
+    const currentQueryParams: { [key: string]: any } = queryString.parse(
```
Comment (nico-bellante) [inline packages/runner/src/pages/Runner/components/App/index.tsx]: much better :)
