### PR TITLE
Fix issue with Office 2016 RTM

### LINKED ISSUE #580: TypeError: Unable to get property 'run' of undefined or null reference
### Bug Report

- **Host**: EXCEL 2016 MSO (16.0.4266.1001) 64-bit, WORD (16.0.4266.1001)  64-bit
- **OS**: Windows 10 Enterprise 1083

#### Expected behavior:

Run/Start the out of the box sample from Script Lab such as "Basic API Call (TypeScript)" sample

#### Actual behavior:

Error Message Pop out "TypeError: Unable to get property 'run' of undefined or null reference"

#### Steps to Reproduce:

1. Install Script Lab Add-ins
2. Choose any sample Script available out of the box
3. Fail with error message "TypeError: Unable to get property 'run' of undefined or null reference"

#### Screenshot:

image

edit 1: add Word as other host, the same behavior occurs in Word's Script Lab

### PR DESCRIPTION
**Pull request by Zlatkovsky**
Fixes #580

### CODE REVIEW

File: packages/editor/src/pages/Editor/index.tsx [hunk 1]
```diff
@@ -63,3 +66,55 @@ class Editor extends Component<{}, IState> {
 }
 
 export default Editor;
+
+///////////////////////////////////////
+
+async function ensureProperOfficeBuildIfRelevant() {
```
Comment (nico-bellante) [inline packages/editor/src/pages/Editor/index.tsx]: Are these ever going to be used elsewhere? / Should the be factored out to a utilities file somewhere?
